-- ============================================================================
-- GENERATED FILE - DO NOT EDIT BY HAND
--
--   layer      : mart / published feature table
--   feature    : fact_agg_features_login_history_v2
--   spec       : features/fact_agg_features_login_history_v2.yml
--   spec hash  : 35c25bc02ee1
--   generator  : featuremart
--
-- Edit the spec and run `make generate`. CI fails when a generated file
-- differs from what the spec produces, so this file and the spec cannot
-- drift apart.
-- ============================================================================

-- One row per entity per as-of date, 480 feature columns wide.
--
-- POINT-IN-TIME SAFETY. Nothing here can see past target_date: the partial
-- layer refuses events after it and every window is bounded above by it, so
-- joining this table to labels on target_date is leak-free by construction.

{{ config(
    materialized='incremental',
    incremental_strategy=fs_partition_replace_strategy(),
    unique_key=['target_date'],
    partition_by=fs_partition_config(['target_date']),
    cluster_by=fs_cluster_config(['target_date']),
    on_schema_change='sync_all_columns',
    tags=['feature_store', 'fact_agg_features_login_history_v2', 'mart']
) }}

with

rollup as (

    select * from {{ ref('int_fact_agg_features_login_history_v2__window_rollup') }}

),

at_state as (

    select * from {{ ref('int_fact_agg_features_login_history_v2__alltime_state') }}

),

at_recent as (

    select * from {{ ref('int_fact_agg_features_login_history_v2__alltime_recent') }}

),

spine as (

    -- entity_spine: active_window. Only entities with activity inside the
    -- widest bounded window (30 days) get a row for this as-of date.
    --
    -- READ THIS BEFORE JOINING. A dormant entity gets NO ROW for this date,
    -- not a row of zeros. Rows are partitioned by target_date, so an equi-join
    -- on (entity, target_date) MISSES for a dormant entity rather than
    -- resolving to an older snapshot -- its last row sits at an earlier
    -- target_date and only a range join would find it.
    --
    -- So the consumer has to decide what a missing row means. Treating it as
    -- genuine inactivity is usually right for count features and wrong for
    -- extrema and all_time, which are not zero for a dormant entity, merely
    -- unpublished. Switch to entity_spine: all_time if that call is not one
    -- the consumers should be making.
    select safe_id from rollup

),

joined as (

    select
        spine.safe_id,

        -- event_id / count ----------------------------------------------------
        coalesce(rollup.count_event_id_l7d, 0) as count_event_id_l7d,
        coalesce(rollup.count_event_id_l14d, 0) as count_event_id_l14d,
        coalesce(rollup.count_event_id_l30d, 0) as count_event_id_l30d,
        coalesce((coalesce(at_state.p_count_event_id, 0) + coalesce(at_recent.p_count_event_id, 0)), 0) as count_event_id_all_time,
        coalesce(rollup.count_event_id_is_late_night_l7d, 0) as count_event_id_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_late_night_l14d, 0) as count_event_id_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_late_night_l30d, 0) as count_event_id_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_late_night, 0)), 0) as count_event_id_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_early_morning_l7d, 0) as count_event_id_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_early_morning_l14d, 0) as count_event_id_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_early_morning_l30d, 0) as count_event_id_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_early_morning, 0)), 0) as count_event_id_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_office_hours_l7d, 0) as count_event_id_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_office_hours_l14d, 0) as count_event_id_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_office_hours_l30d, 0) as count_event_id_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_office_hours, 0)), 0) as count_event_id_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_evening_leisure_l7d, 0) as count_event_id_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_evening_leisure_l14d, 0) as count_event_id_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_evening_leisure_l30d, 0) as count_event_id_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_evening_leisure, 0)), 0) as count_event_id_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_ios_l7d, 0) as count_event_id_is_ios_l7d,
        coalesce(rollup.count_event_id_is_ios_l14d, 0) as count_event_id_is_ios_l14d,
        coalesce(rollup.count_event_id_is_ios_l30d, 0) as count_event_id_is_ios_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_ios, 0) + coalesce(at_recent.p_count_event_id_is_ios, 0)), 0) as count_event_id_is_ios_all_time,
        coalesce(rollup.count_event_id_is_ios_is_late_night_l7d, 0) as count_event_id_is_ios_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_ios_is_late_night_l14d, 0) as count_event_id_is_ios_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_ios_is_late_night_l30d, 0) as count_event_id_is_ios_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_ios_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_ios_is_late_night, 0)), 0) as count_event_id_is_ios_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_ios_is_early_morning_l7d, 0) as count_event_id_is_ios_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_ios_is_early_morning_l14d, 0) as count_event_id_is_ios_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_ios_is_early_morning_l30d, 0) as count_event_id_is_ios_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_ios_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_ios_is_early_morning, 0)), 0) as count_event_id_is_ios_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_ios_is_office_hours_l7d, 0) as count_event_id_is_ios_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_ios_is_office_hours_l14d, 0) as count_event_id_is_ios_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_ios_is_office_hours_l30d, 0) as count_event_id_is_ios_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_ios_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_ios_is_office_hours, 0)), 0) as count_event_id_is_ios_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_ios_is_evening_leisure_l7d, 0) as count_event_id_is_ios_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_ios_is_evening_leisure_l14d, 0) as count_event_id_is_ios_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_ios_is_evening_leisure_l30d, 0) as count_event_id_is_ios_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_ios_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_ios_is_evening_leisure, 0)), 0) as count_event_id_is_ios_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_android_l7d, 0) as count_event_id_is_android_l7d,
        coalesce(rollup.count_event_id_is_android_l14d, 0) as count_event_id_is_android_l14d,
        coalesce(rollup.count_event_id_is_android_l30d, 0) as count_event_id_is_android_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_android, 0) + coalesce(at_recent.p_count_event_id_is_android, 0)), 0) as count_event_id_is_android_all_time,
        coalesce(rollup.count_event_id_is_android_is_late_night_l7d, 0) as count_event_id_is_android_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_android_is_late_night_l14d, 0) as count_event_id_is_android_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_android_is_late_night_l30d, 0) as count_event_id_is_android_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_android_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_android_is_late_night, 0)), 0) as count_event_id_is_android_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_android_is_early_morning_l7d, 0) as count_event_id_is_android_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_android_is_early_morning_l14d, 0) as count_event_id_is_android_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_android_is_early_morning_l30d, 0) as count_event_id_is_android_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_android_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_android_is_early_morning, 0)), 0) as count_event_id_is_android_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_android_is_office_hours_l7d, 0) as count_event_id_is_android_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_android_is_office_hours_l14d, 0) as count_event_id_is_android_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_android_is_office_hours_l30d, 0) as count_event_id_is_android_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_android_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_android_is_office_hours, 0)), 0) as count_event_id_is_android_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_android_is_evening_leisure_l7d, 0) as count_event_id_is_android_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_android_is_evening_leisure_l14d, 0) as count_event_id_is_android_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_android_is_evening_leisure_l30d, 0) as count_event_id_is_android_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_android_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_android_is_evening_leisure, 0)), 0) as count_event_id_is_android_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_others_l7d, 0) as count_event_id_is_others_l7d,
        coalesce(rollup.count_event_id_is_others_l14d, 0) as count_event_id_is_others_l14d,
        coalesce(rollup.count_event_id_is_others_l30d, 0) as count_event_id_is_others_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_others, 0) + coalesce(at_recent.p_count_event_id_is_others, 0)), 0) as count_event_id_is_others_all_time,
        coalesce(rollup.count_event_id_is_others_is_late_night_l7d, 0) as count_event_id_is_others_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_others_is_late_night_l14d, 0) as count_event_id_is_others_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_others_is_late_night_l30d, 0) as count_event_id_is_others_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_others_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_others_is_late_night, 0)), 0) as count_event_id_is_others_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_others_is_early_morning_l7d, 0) as count_event_id_is_others_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_others_is_early_morning_l14d, 0) as count_event_id_is_others_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_others_is_early_morning_l30d, 0) as count_event_id_is_others_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_others_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_others_is_early_morning, 0)), 0) as count_event_id_is_others_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_others_is_office_hours_l7d, 0) as count_event_id_is_others_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_others_is_office_hours_l14d, 0) as count_event_id_is_others_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_others_is_office_hours_l30d, 0) as count_event_id_is_others_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_others_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_others_is_office_hours, 0)), 0) as count_event_id_is_others_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_others_is_evening_leisure_l7d, 0) as count_event_id_is_others_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_others_is_evening_leisure_l14d, 0) as count_event_id_is_others_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_others_is_evening_leisure_l30d, 0) as count_event_id_is_others_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_others_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_others_is_evening_leisure, 0)), 0) as count_event_id_is_others_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_success_l7d, 0) as count_event_id_is_login_success_l7d,
        coalesce(rollup.count_event_id_is_login_success_l14d, 0) as count_event_id_is_login_success_l14d,
        coalesce(rollup.count_event_id_is_login_success_l30d, 0) as count_event_id_is_login_success_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success, 0) + coalesce(at_recent.p_count_event_id_is_login_success, 0)), 0) as count_event_id_is_login_success_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_late_night_l7d, 0) as count_event_id_is_login_success_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_late_night_l14d, 0) as count_event_id_is_login_success_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_late_night_l30d, 0) as count_event_id_is_login_success_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_late_night, 0)), 0) as count_event_id_is_login_success_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_early_morning_l7d, 0) as count_event_id_is_login_success_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_early_morning_l14d, 0) as count_event_id_is_login_success_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_early_morning_l30d, 0) as count_event_id_is_login_success_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_early_morning, 0)), 0) as count_event_id_is_login_success_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_office_hours_l7d, 0) as count_event_id_is_login_success_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_office_hours_l14d, 0) as count_event_id_is_login_success_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_office_hours_l30d, 0) as count_event_id_is_login_success_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_office_hours, 0)), 0) as count_event_id_is_login_success_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_evening_leisure_l7d, 0) as count_event_id_is_login_success_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_evening_leisure_l14d, 0) as count_event_id_is_login_success_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_evening_leisure_l30d, 0) as count_event_id_is_login_success_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_evening_leisure, 0)), 0) as count_event_id_is_login_success_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_ios_l7d, 0) as count_event_id_is_login_success_is_ios_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_l14d, 0) as count_event_id_is_login_success_is_ios_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_l30d, 0) as count_event_id_is_login_success_is_ios_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_ios, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_ios, 0)), 0) as count_event_id_is_login_success_is_ios_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_late_night_l7d, 0) as count_event_id_is_login_success_is_ios_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_late_night_l14d, 0) as count_event_id_is_login_success_is_ios_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_late_night_l30d, 0) as count_event_id_is_login_success_is_ios_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_ios_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_ios_is_late_night, 0)), 0) as count_event_id_is_login_success_is_ios_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_early_morning_l7d, 0) as count_event_id_is_login_success_is_ios_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_early_morning_l14d, 0) as count_event_id_is_login_success_is_ios_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_early_morning_l30d, 0) as count_event_id_is_login_success_is_ios_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_ios_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_ios_is_early_morning, 0)), 0) as count_event_id_is_login_success_is_ios_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_office_hours_l7d, 0) as count_event_id_is_login_success_is_ios_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_office_hours_l14d, 0) as count_event_id_is_login_success_is_ios_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_office_hours_l30d, 0) as count_event_id_is_login_success_is_ios_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_ios_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_ios_is_office_hours, 0)), 0) as count_event_id_is_login_success_is_ios_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_evening_leisure_l7d, 0) as count_event_id_is_login_success_is_ios_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_evening_leisure_l14d, 0) as count_event_id_is_login_success_is_ios_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_ios_is_evening_leisure_l30d, 0) as count_event_id_is_login_success_is_ios_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_ios_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_ios_is_evening_leisure, 0)), 0) as count_event_id_is_login_success_is_ios_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_android_l7d, 0) as count_event_id_is_login_success_is_android_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_android_l14d, 0) as count_event_id_is_login_success_is_android_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_android_l30d, 0) as count_event_id_is_login_success_is_android_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_android, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_android, 0)), 0) as count_event_id_is_login_success_is_android_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_late_night_l7d, 0) as count_event_id_is_login_success_is_android_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_late_night_l14d, 0) as count_event_id_is_login_success_is_android_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_late_night_l30d, 0) as count_event_id_is_login_success_is_android_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_android_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_android_is_late_night, 0)), 0) as count_event_id_is_login_success_is_android_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_early_morning_l7d, 0) as count_event_id_is_login_success_is_android_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_early_morning_l14d, 0) as count_event_id_is_login_success_is_android_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_early_morning_l30d, 0) as count_event_id_is_login_success_is_android_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_android_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_android_is_early_morning, 0)), 0) as count_event_id_is_login_success_is_android_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_office_hours_l7d, 0) as count_event_id_is_login_success_is_android_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_office_hours_l14d, 0) as count_event_id_is_login_success_is_android_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_office_hours_l30d, 0) as count_event_id_is_login_success_is_android_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_android_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_android_is_office_hours, 0)), 0) as count_event_id_is_login_success_is_android_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_evening_leisure_l7d, 0) as count_event_id_is_login_success_is_android_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_evening_leisure_l14d, 0) as count_event_id_is_login_success_is_android_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_android_is_evening_leisure_l30d, 0) as count_event_id_is_login_success_is_android_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_android_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_android_is_evening_leisure, 0)), 0) as count_event_id_is_login_success_is_android_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_others_l7d, 0) as count_event_id_is_login_success_is_others_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_others_l14d, 0) as count_event_id_is_login_success_is_others_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_others_l30d, 0) as count_event_id_is_login_success_is_others_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_others, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_others, 0)), 0) as count_event_id_is_login_success_is_others_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_late_night_l7d, 0) as count_event_id_is_login_success_is_others_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_late_night_l14d, 0) as count_event_id_is_login_success_is_others_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_late_night_l30d, 0) as count_event_id_is_login_success_is_others_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_others_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_others_is_late_night, 0)), 0) as count_event_id_is_login_success_is_others_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_early_morning_l7d, 0) as count_event_id_is_login_success_is_others_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_early_morning_l14d, 0) as count_event_id_is_login_success_is_others_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_early_morning_l30d, 0) as count_event_id_is_login_success_is_others_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_others_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_others_is_early_morning, 0)), 0) as count_event_id_is_login_success_is_others_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_office_hours_l7d, 0) as count_event_id_is_login_success_is_others_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_office_hours_l14d, 0) as count_event_id_is_login_success_is_others_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_office_hours_l30d, 0) as count_event_id_is_login_success_is_others_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_others_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_others_is_office_hours, 0)), 0) as count_event_id_is_login_success_is_others_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_evening_leisure_l7d, 0) as count_event_id_is_login_success_is_others_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_evening_leisure_l14d, 0) as count_event_id_is_login_success_is_others_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_success_is_others_is_evening_leisure_l30d, 0) as count_event_id_is_login_success_is_others_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_success_is_others_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_success_is_others_is_evening_leisure, 0)), 0) as count_event_id_is_login_success_is_others_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_failed_l7d, 0) as count_event_id_is_login_failed_l7d,
        coalesce(rollup.count_event_id_is_login_failed_l14d, 0) as count_event_id_is_login_failed_l14d,
        coalesce(rollup.count_event_id_is_login_failed_l30d, 0) as count_event_id_is_login_failed_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed, 0) + coalesce(at_recent.p_count_event_id_is_login_failed, 0)), 0) as count_event_id_is_login_failed_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_late_night_l7d, 0) as count_event_id_is_login_failed_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_late_night_l14d, 0) as count_event_id_is_login_failed_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_late_night_l30d, 0) as count_event_id_is_login_failed_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_late_night, 0)), 0) as count_event_id_is_login_failed_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_early_morning_l7d, 0) as count_event_id_is_login_failed_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_early_morning_l14d, 0) as count_event_id_is_login_failed_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_early_morning_l30d, 0) as count_event_id_is_login_failed_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_early_morning, 0)), 0) as count_event_id_is_login_failed_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_office_hours_l7d, 0) as count_event_id_is_login_failed_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_office_hours_l14d, 0) as count_event_id_is_login_failed_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_office_hours_l30d, 0) as count_event_id_is_login_failed_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_office_hours, 0)), 0) as count_event_id_is_login_failed_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_evening_leisure_l7d, 0) as count_event_id_is_login_failed_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_evening_leisure_l14d, 0) as count_event_id_is_login_failed_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_evening_leisure_l30d, 0) as count_event_id_is_login_failed_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_evening_leisure, 0)), 0) as count_event_id_is_login_failed_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_l7d, 0) as count_event_id_is_login_failed_is_ios_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_l14d, 0) as count_event_id_is_login_failed_is_ios_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_l30d, 0) as count_event_id_is_login_failed_is_ios_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_ios, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_ios, 0)), 0) as count_event_id_is_login_failed_is_ios_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_late_night_l7d, 0) as count_event_id_is_login_failed_is_ios_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_late_night_l14d, 0) as count_event_id_is_login_failed_is_ios_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_late_night_l30d, 0) as count_event_id_is_login_failed_is_ios_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_ios_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_ios_is_late_night, 0)), 0) as count_event_id_is_login_failed_is_ios_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_early_morning_l7d, 0) as count_event_id_is_login_failed_is_ios_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_early_morning_l14d, 0) as count_event_id_is_login_failed_is_ios_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_early_morning_l30d, 0) as count_event_id_is_login_failed_is_ios_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_ios_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_ios_is_early_morning, 0)), 0) as count_event_id_is_login_failed_is_ios_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_office_hours_l7d, 0) as count_event_id_is_login_failed_is_ios_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_office_hours_l14d, 0) as count_event_id_is_login_failed_is_ios_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_office_hours_l30d, 0) as count_event_id_is_login_failed_is_ios_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_ios_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_ios_is_office_hours, 0)), 0) as count_event_id_is_login_failed_is_ios_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_evening_leisure_l7d, 0) as count_event_id_is_login_failed_is_ios_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_evening_leisure_l14d, 0) as count_event_id_is_login_failed_is_ios_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_ios_is_evening_leisure_l30d, 0) as count_event_id_is_login_failed_is_ios_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_ios_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_ios_is_evening_leisure, 0)), 0) as count_event_id_is_login_failed_is_ios_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_android_l7d, 0) as count_event_id_is_login_failed_is_android_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_l14d, 0) as count_event_id_is_login_failed_is_android_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_l30d, 0) as count_event_id_is_login_failed_is_android_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_android, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_android, 0)), 0) as count_event_id_is_login_failed_is_android_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_late_night_l7d, 0) as count_event_id_is_login_failed_is_android_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_late_night_l14d, 0) as count_event_id_is_login_failed_is_android_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_late_night_l30d, 0) as count_event_id_is_login_failed_is_android_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_android_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_android_is_late_night, 0)), 0) as count_event_id_is_login_failed_is_android_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_early_morning_l7d, 0) as count_event_id_is_login_failed_is_android_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_early_morning_l14d, 0) as count_event_id_is_login_failed_is_android_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_early_morning_l30d, 0) as count_event_id_is_login_failed_is_android_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_android_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_android_is_early_morning, 0)), 0) as count_event_id_is_login_failed_is_android_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_office_hours_l7d, 0) as count_event_id_is_login_failed_is_android_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_office_hours_l14d, 0) as count_event_id_is_login_failed_is_android_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_office_hours_l30d, 0) as count_event_id_is_login_failed_is_android_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_android_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_android_is_office_hours, 0)), 0) as count_event_id_is_login_failed_is_android_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_evening_leisure_l7d, 0) as count_event_id_is_login_failed_is_android_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_evening_leisure_l14d, 0) as count_event_id_is_login_failed_is_android_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_android_is_evening_leisure_l30d, 0) as count_event_id_is_login_failed_is_android_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_android_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_android_is_evening_leisure, 0)), 0) as count_event_id_is_login_failed_is_android_is_evening_leisure_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_others_l7d, 0) as count_event_id_is_login_failed_is_others_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_l14d, 0) as count_event_id_is_login_failed_is_others_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_l30d, 0) as count_event_id_is_login_failed_is_others_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_others, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_others, 0)), 0) as count_event_id_is_login_failed_is_others_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_late_night_l7d, 0) as count_event_id_is_login_failed_is_others_is_late_night_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_late_night_l14d, 0) as count_event_id_is_login_failed_is_others_is_late_night_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_late_night_l30d, 0) as count_event_id_is_login_failed_is_others_is_late_night_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_others_is_late_night, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_others_is_late_night, 0)), 0) as count_event_id_is_login_failed_is_others_is_late_night_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_early_morning_l7d, 0) as count_event_id_is_login_failed_is_others_is_early_morning_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_early_morning_l14d, 0) as count_event_id_is_login_failed_is_others_is_early_morning_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_early_morning_l30d, 0) as count_event_id_is_login_failed_is_others_is_early_morning_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_others_is_early_morning, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_others_is_early_morning, 0)), 0) as count_event_id_is_login_failed_is_others_is_early_morning_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_office_hours_l7d, 0) as count_event_id_is_login_failed_is_others_is_office_hours_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_office_hours_l14d, 0) as count_event_id_is_login_failed_is_others_is_office_hours_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_office_hours_l30d, 0) as count_event_id_is_login_failed_is_others_is_office_hours_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_others_is_office_hours, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_others_is_office_hours, 0)), 0) as count_event_id_is_login_failed_is_others_is_office_hours_all_time,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_evening_leisure_l7d, 0) as count_event_id_is_login_failed_is_others_is_evening_leisure_l7d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_evening_leisure_l14d, 0) as count_event_id_is_login_failed_is_others_is_evening_leisure_l14d,
        coalesce(rollup.count_event_id_is_login_failed_is_others_is_evening_leisure_l30d, 0) as count_event_id_is_login_failed_is_others_is_evening_leisure_l30d,
        coalesce((coalesce(at_state.p_count_event_id_is_login_failed_is_others_is_evening_leisure, 0) + coalesce(at_recent.p_count_event_id_is_login_failed_is_others_is_evening_leisure, 0)), 0) as count_event_id_is_login_failed_is_others_is_evening_leisure_all_time,

        -- device_id / count_distinct ------------------------------------------
        coalesce(rollup.count_distinct_device_id_l7d, 0) as count_distinct_device_id_l7d,
        coalesce(rollup.count_distinct_device_id_l14d, 0) as count_distinct_device_id_l14d,
        coalesce(rollup.count_distinct_device_id_l30d, 0) as count_distinct_device_id_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id", "at_recent.p_count_distinct_device_id")) }} as count_distinct_device_id_all_time,
        coalesce(rollup.count_distinct_device_id_is_ios_l7d, 0) as count_distinct_device_id_is_ios_l7d,
        coalesce(rollup.count_distinct_device_id_is_ios_l14d, 0) as count_distinct_device_id_is_ios_l14d,
        coalesce(rollup.count_distinct_device_id_is_ios_l30d, 0) as count_distinct_device_id_is_ios_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_ios", "at_recent.p_count_distinct_device_id_is_ios")) }} as count_distinct_device_id_is_ios_all_time,
        coalesce(rollup.count_distinct_device_id_is_android_l7d, 0) as count_distinct_device_id_is_android_l7d,
        coalesce(rollup.count_distinct_device_id_is_android_l14d, 0) as count_distinct_device_id_is_android_l14d,
        coalesce(rollup.count_distinct_device_id_is_android_l30d, 0) as count_distinct_device_id_is_android_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_android", "at_recent.p_count_distinct_device_id_is_android")) }} as count_distinct_device_id_is_android_all_time,
        coalesce(rollup.count_distinct_device_id_is_others_l7d, 0) as count_distinct_device_id_is_others_l7d,
        coalesce(rollup.count_distinct_device_id_is_others_l14d, 0) as count_distinct_device_id_is_others_l14d,
        coalesce(rollup.count_distinct_device_id_is_others_l30d, 0) as count_distinct_device_id_is_others_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_others", "at_recent.p_count_distinct_device_id_is_others")) }} as count_distinct_device_id_is_others_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_success_l7d, 0) as count_distinct_device_id_is_login_success_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_success_l14d, 0) as count_distinct_device_id_is_login_success_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_success_l30d, 0) as count_distinct_device_id_is_login_success_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_success", "at_recent.p_count_distinct_device_id_is_login_success")) }} as count_distinct_device_id_is_login_success_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_ios_l7d, 0) as count_distinct_device_id_is_login_success_is_ios_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_ios_l14d, 0) as count_distinct_device_id_is_login_success_is_ios_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_ios_l30d, 0) as count_distinct_device_id_is_login_success_is_ios_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_success_is_ios", "at_recent.p_count_distinct_device_id_is_login_success_is_ios")) }} as count_distinct_device_id_is_login_success_is_ios_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_android_l7d, 0) as count_distinct_device_id_is_login_success_is_android_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_android_l14d, 0) as count_distinct_device_id_is_login_success_is_android_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_android_l30d, 0) as count_distinct_device_id_is_login_success_is_android_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_success_is_android", "at_recent.p_count_distinct_device_id_is_login_success_is_android")) }} as count_distinct_device_id_is_login_success_is_android_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_others_l7d, 0) as count_distinct_device_id_is_login_success_is_others_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_others_l14d, 0) as count_distinct_device_id_is_login_success_is_others_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_success_is_others_l30d, 0) as count_distinct_device_id_is_login_success_is_others_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_success_is_others", "at_recent.p_count_distinct_device_id_is_login_success_is_others")) }} as count_distinct_device_id_is_login_success_is_others_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_failed_l7d, 0) as count_distinct_device_id_is_login_failed_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_l14d, 0) as count_distinct_device_id_is_login_failed_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_l30d, 0) as count_distinct_device_id_is_login_failed_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_failed", "at_recent.p_count_distinct_device_id_is_login_failed")) }} as count_distinct_device_id_is_login_failed_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_ios_l7d, 0) as count_distinct_device_id_is_login_failed_is_ios_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_ios_l14d, 0) as count_distinct_device_id_is_login_failed_is_ios_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_ios_l30d, 0) as count_distinct_device_id_is_login_failed_is_ios_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_failed_is_ios", "at_recent.p_count_distinct_device_id_is_login_failed_is_ios")) }} as count_distinct_device_id_is_login_failed_is_ios_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_android_l7d, 0) as count_distinct_device_id_is_login_failed_is_android_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_android_l14d, 0) as count_distinct_device_id_is_login_failed_is_android_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_android_l30d, 0) as count_distinct_device_id_is_login_failed_is_android_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_failed_is_android", "at_recent.p_count_distinct_device_id_is_login_failed_is_android")) }} as count_distinct_device_id_is_login_failed_is_android_all_time,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_others_l7d, 0) as count_distinct_device_id_is_login_failed_is_others_l7d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_others_l14d, 0) as count_distinct_device_id_is_login_failed_is_others_l14d,
        coalesce(rollup.count_distinct_device_id_is_login_failed_is_others_l30d, 0) as count_distinct_device_id_is_login_failed_is_others_l30d,
        {{ fs_array_size(fs_array_union2("at_state.p_count_distinct_device_id_is_login_failed_is_others", "at_recent.p_count_distinct_device_id_is_login_failed_is_others")) }} as count_distinct_device_id_is_login_failed_is_others_all_time,

        -- event_timestamp / min -----------------------------------------------
        rollup.min_event_timestamp_l7d as min_event_timestamp_l7d,
        rollup.min_event_timestamp_l14d as min_event_timestamp_l14d,
        rollup.min_event_timestamp_l30d as min_event_timestamp_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp", "at_recent.p_min_event_timestamp") }} as min_event_timestamp_all_time,
        rollup.min_event_timestamp_is_ios_l7d as min_event_timestamp_is_ios_l7d,
        rollup.min_event_timestamp_is_ios_l14d as min_event_timestamp_is_ios_l14d,
        rollup.min_event_timestamp_is_ios_l30d as min_event_timestamp_is_ios_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_ios", "at_recent.p_min_event_timestamp_is_ios") }} as min_event_timestamp_is_ios_all_time,
        rollup.min_event_timestamp_is_android_l7d as min_event_timestamp_is_android_l7d,
        rollup.min_event_timestamp_is_android_l14d as min_event_timestamp_is_android_l14d,
        rollup.min_event_timestamp_is_android_l30d as min_event_timestamp_is_android_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_android", "at_recent.p_min_event_timestamp_is_android") }} as min_event_timestamp_is_android_all_time,
        rollup.min_event_timestamp_is_others_l7d as min_event_timestamp_is_others_l7d,
        rollup.min_event_timestamp_is_others_l14d as min_event_timestamp_is_others_l14d,
        rollup.min_event_timestamp_is_others_l30d as min_event_timestamp_is_others_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_others", "at_recent.p_min_event_timestamp_is_others") }} as min_event_timestamp_is_others_all_time,
        rollup.min_event_timestamp_is_login_success_l7d as min_event_timestamp_is_login_success_l7d,
        rollup.min_event_timestamp_is_login_success_l14d as min_event_timestamp_is_login_success_l14d,
        rollup.min_event_timestamp_is_login_success_l30d as min_event_timestamp_is_login_success_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_success", "at_recent.p_min_event_timestamp_is_login_success") }} as min_event_timestamp_is_login_success_all_time,
        rollup.min_event_timestamp_is_login_success_is_ios_l7d as min_event_timestamp_is_login_success_is_ios_l7d,
        rollup.min_event_timestamp_is_login_success_is_ios_l14d as min_event_timestamp_is_login_success_is_ios_l14d,
        rollup.min_event_timestamp_is_login_success_is_ios_l30d as min_event_timestamp_is_login_success_is_ios_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_success_is_ios", "at_recent.p_min_event_timestamp_is_login_success_is_ios") }} as min_event_timestamp_is_login_success_is_ios_all_time,
        rollup.min_event_timestamp_is_login_success_is_android_l7d as min_event_timestamp_is_login_success_is_android_l7d,
        rollup.min_event_timestamp_is_login_success_is_android_l14d as min_event_timestamp_is_login_success_is_android_l14d,
        rollup.min_event_timestamp_is_login_success_is_android_l30d as min_event_timestamp_is_login_success_is_android_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_success_is_android", "at_recent.p_min_event_timestamp_is_login_success_is_android") }} as min_event_timestamp_is_login_success_is_android_all_time,
        rollup.min_event_timestamp_is_login_success_is_others_l7d as min_event_timestamp_is_login_success_is_others_l7d,
        rollup.min_event_timestamp_is_login_success_is_others_l14d as min_event_timestamp_is_login_success_is_others_l14d,
        rollup.min_event_timestamp_is_login_success_is_others_l30d as min_event_timestamp_is_login_success_is_others_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_success_is_others", "at_recent.p_min_event_timestamp_is_login_success_is_others") }} as min_event_timestamp_is_login_success_is_others_all_time,
        rollup.min_event_timestamp_is_login_failed_l7d as min_event_timestamp_is_login_failed_l7d,
        rollup.min_event_timestamp_is_login_failed_l14d as min_event_timestamp_is_login_failed_l14d,
        rollup.min_event_timestamp_is_login_failed_l30d as min_event_timestamp_is_login_failed_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_failed", "at_recent.p_min_event_timestamp_is_login_failed") }} as min_event_timestamp_is_login_failed_all_time,
        rollup.min_event_timestamp_is_login_failed_is_ios_l7d as min_event_timestamp_is_login_failed_is_ios_l7d,
        rollup.min_event_timestamp_is_login_failed_is_ios_l14d as min_event_timestamp_is_login_failed_is_ios_l14d,
        rollup.min_event_timestamp_is_login_failed_is_ios_l30d as min_event_timestamp_is_login_failed_is_ios_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_failed_is_ios", "at_recent.p_min_event_timestamp_is_login_failed_is_ios") }} as min_event_timestamp_is_login_failed_is_ios_all_time,
        rollup.min_event_timestamp_is_login_failed_is_android_l7d as min_event_timestamp_is_login_failed_is_android_l7d,
        rollup.min_event_timestamp_is_login_failed_is_android_l14d as min_event_timestamp_is_login_failed_is_android_l14d,
        rollup.min_event_timestamp_is_login_failed_is_android_l30d as min_event_timestamp_is_login_failed_is_android_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_failed_is_android", "at_recent.p_min_event_timestamp_is_login_failed_is_android") }} as min_event_timestamp_is_login_failed_is_android_all_time,
        rollup.min_event_timestamp_is_login_failed_is_others_l7d as min_event_timestamp_is_login_failed_is_others_l7d,
        rollup.min_event_timestamp_is_login_failed_is_others_l14d as min_event_timestamp_is_login_failed_is_others_l14d,
        rollup.min_event_timestamp_is_login_failed_is_others_l30d as min_event_timestamp_is_login_failed_is_others_l30d,
        {{ fs_least2("at_state.p_min_event_timestamp_is_login_failed_is_others", "at_recent.p_min_event_timestamp_is_login_failed_is_others") }} as min_event_timestamp_is_login_failed_is_others_all_time,

        -- event_timestamp / max -----------------------------------------------
        rollup.max_event_timestamp_l7d as max_event_timestamp_l7d,
        rollup.max_event_timestamp_l14d as max_event_timestamp_l14d,
        rollup.max_event_timestamp_l30d as max_event_timestamp_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp", "at_recent.p_max_event_timestamp") }} as max_event_timestamp_all_time,
        rollup.max_event_timestamp_is_ios_l7d as max_event_timestamp_is_ios_l7d,
        rollup.max_event_timestamp_is_ios_l14d as max_event_timestamp_is_ios_l14d,
        rollup.max_event_timestamp_is_ios_l30d as max_event_timestamp_is_ios_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_ios", "at_recent.p_max_event_timestamp_is_ios") }} as max_event_timestamp_is_ios_all_time,
        rollup.max_event_timestamp_is_android_l7d as max_event_timestamp_is_android_l7d,
        rollup.max_event_timestamp_is_android_l14d as max_event_timestamp_is_android_l14d,
        rollup.max_event_timestamp_is_android_l30d as max_event_timestamp_is_android_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_android", "at_recent.p_max_event_timestamp_is_android") }} as max_event_timestamp_is_android_all_time,
        rollup.max_event_timestamp_is_others_l7d as max_event_timestamp_is_others_l7d,
        rollup.max_event_timestamp_is_others_l14d as max_event_timestamp_is_others_l14d,
        rollup.max_event_timestamp_is_others_l30d as max_event_timestamp_is_others_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_others", "at_recent.p_max_event_timestamp_is_others") }} as max_event_timestamp_is_others_all_time,
        rollup.max_event_timestamp_is_login_success_l7d as max_event_timestamp_is_login_success_l7d,
        rollup.max_event_timestamp_is_login_success_l14d as max_event_timestamp_is_login_success_l14d,
        rollup.max_event_timestamp_is_login_success_l30d as max_event_timestamp_is_login_success_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_success", "at_recent.p_max_event_timestamp_is_login_success") }} as max_event_timestamp_is_login_success_all_time,
        rollup.max_event_timestamp_is_login_success_is_ios_l7d as max_event_timestamp_is_login_success_is_ios_l7d,
        rollup.max_event_timestamp_is_login_success_is_ios_l14d as max_event_timestamp_is_login_success_is_ios_l14d,
        rollup.max_event_timestamp_is_login_success_is_ios_l30d as max_event_timestamp_is_login_success_is_ios_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_success_is_ios", "at_recent.p_max_event_timestamp_is_login_success_is_ios") }} as max_event_timestamp_is_login_success_is_ios_all_time,
        rollup.max_event_timestamp_is_login_success_is_android_l7d as max_event_timestamp_is_login_success_is_android_l7d,
        rollup.max_event_timestamp_is_login_success_is_android_l14d as max_event_timestamp_is_login_success_is_android_l14d,
        rollup.max_event_timestamp_is_login_success_is_android_l30d as max_event_timestamp_is_login_success_is_android_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_success_is_android", "at_recent.p_max_event_timestamp_is_login_success_is_android") }} as max_event_timestamp_is_login_success_is_android_all_time,
        rollup.max_event_timestamp_is_login_success_is_others_l7d as max_event_timestamp_is_login_success_is_others_l7d,
        rollup.max_event_timestamp_is_login_success_is_others_l14d as max_event_timestamp_is_login_success_is_others_l14d,
        rollup.max_event_timestamp_is_login_success_is_others_l30d as max_event_timestamp_is_login_success_is_others_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_success_is_others", "at_recent.p_max_event_timestamp_is_login_success_is_others") }} as max_event_timestamp_is_login_success_is_others_all_time,
        rollup.max_event_timestamp_is_login_failed_l7d as max_event_timestamp_is_login_failed_l7d,
        rollup.max_event_timestamp_is_login_failed_l14d as max_event_timestamp_is_login_failed_l14d,
        rollup.max_event_timestamp_is_login_failed_l30d as max_event_timestamp_is_login_failed_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_failed", "at_recent.p_max_event_timestamp_is_login_failed") }} as max_event_timestamp_is_login_failed_all_time,
        rollup.max_event_timestamp_is_login_failed_is_ios_l7d as max_event_timestamp_is_login_failed_is_ios_l7d,
        rollup.max_event_timestamp_is_login_failed_is_ios_l14d as max_event_timestamp_is_login_failed_is_ios_l14d,
        rollup.max_event_timestamp_is_login_failed_is_ios_l30d as max_event_timestamp_is_login_failed_is_ios_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_failed_is_ios", "at_recent.p_max_event_timestamp_is_login_failed_is_ios") }} as max_event_timestamp_is_login_failed_is_ios_all_time,
        rollup.max_event_timestamp_is_login_failed_is_android_l7d as max_event_timestamp_is_login_failed_is_android_l7d,
        rollup.max_event_timestamp_is_login_failed_is_android_l14d as max_event_timestamp_is_login_failed_is_android_l14d,
        rollup.max_event_timestamp_is_login_failed_is_android_l30d as max_event_timestamp_is_login_failed_is_android_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_failed_is_android", "at_recent.p_max_event_timestamp_is_login_failed_is_android") }} as max_event_timestamp_is_login_failed_is_android_all_time,
        rollup.max_event_timestamp_is_login_failed_is_others_l7d as max_event_timestamp_is_login_failed_is_others_l7d,
        rollup.max_event_timestamp_is_login_failed_is_others_l14d as max_event_timestamp_is_login_failed_is_others_l14d,
        rollup.max_event_timestamp_is_login_failed_is_others_l30d as max_event_timestamp_is_login_failed_is_others_l30d,
        {{ fs_greatest2("at_state.p_max_event_timestamp_is_login_failed_is_others", "at_recent.p_max_event_timestamp_is_login_failed_is_others") }} as max_event_timestamp_is_login_failed_is_others_all_time,

        {{ fs_least2('at_state._min_event_date', 'at_recent._min_event_date') }} as _first_event_date,
        {{ fs_greatest2('at_state._max_event_date', 'at_recent._max_event_date') }} as _last_event_date
    from spine
    left join rollup on spine.safe_id = rollup.safe_id
    left join at_state on spine.safe_id = at_state.safe_id
    left join at_recent on spine.safe_id = at_recent.safe_id

)

select
    {{ fs_target_date() }} as target_date,
    safe_id,

    -- event_id / count ----------------------------------------------------
    count_event_id_l7d,
    count_event_id_l14d,
    count_event_id_l30d,
    count_event_id_all_time,
    count_event_id_is_late_night_l7d,
    count_event_id_is_late_night_l14d,
    count_event_id_is_late_night_l30d,
    count_event_id_is_late_night_all_time,
    count_event_id_is_early_morning_l7d,
    count_event_id_is_early_morning_l14d,
    count_event_id_is_early_morning_l30d,
    count_event_id_is_early_morning_all_time,
    count_event_id_is_office_hours_l7d,
    count_event_id_is_office_hours_l14d,
    count_event_id_is_office_hours_l30d,
    count_event_id_is_office_hours_all_time,
    count_event_id_is_evening_leisure_l7d,
    count_event_id_is_evening_leisure_l14d,
    count_event_id_is_evening_leisure_l30d,
    count_event_id_is_evening_leisure_all_time,
    count_event_id_is_ios_l7d,
    count_event_id_is_ios_l14d,
    count_event_id_is_ios_l30d,
    count_event_id_is_ios_all_time,
    count_event_id_is_ios_is_late_night_l7d,
    count_event_id_is_ios_is_late_night_l14d,
    count_event_id_is_ios_is_late_night_l30d,
    count_event_id_is_ios_is_late_night_all_time,
    count_event_id_is_ios_is_early_morning_l7d,
    count_event_id_is_ios_is_early_morning_l14d,
    count_event_id_is_ios_is_early_morning_l30d,
    count_event_id_is_ios_is_early_morning_all_time,
    count_event_id_is_ios_is_office_hours_l7d,
    count_event_id_is_ios_is_office_hours_l14d,
    count_event_id_is_ios_is_office_hours_l30d,
    count_event_id_is_ios_is_office_hours_all_time,
    count_event_id_is_ios_is_evening_leisure_l7d,
    count_event_id_is_ios_is_evening_leisure_l14d,
    count_event_id_is_ios_is_evening_leisure_l30d,
    count_event_id_is_ios_is_evening_leisure_all_time,
    count_event_id_is_android_l7d,
    count_event_id_is_android_l14d,
    count_event_id_is_android_l30d,
    count_event_id_is_android_all_time,
    count_event_id_is_android_is_late_night_l7d,
    count_event_id_is_android_is_late_night_l14d,
    count_event_id_is_android_is_late_night_l30d,
    count_event_id_is_android_is_late_night_all_time,
    count_event_id_is_android_is_early_morning_l7d,
    count_event_id_is_android_is_early_morning_l14d,
    count_event_id_is_android_is_early_morning_l30d,
    count_event_id_is_android_is_early_morning_all_time,
    count_event_id_is_android_is_office_hours_l7d,
    count_event_id_is_android_is_office_hours_l14d,
    count_event_id_is_android_is_office_hours_l30d,
    count_event_id_is_android_is_office_hours_all_time,
    count_event_id_is_android_is_evening_leisure_l7d,
    count_event_id_is_android_is_evening_leisure_l14d,
    count_event_id_is_android_is_evening_leisure_l30d,
    count_event_id_is_android_is_evening_leisure_all_time,
    count_event_id_is_others_l7d,
    count_event_id_is_others_l14d,
    count_event_id_is_others_l30d,
    count_event_id_is_others_all_time,
    count_event_id_is_others_is_late_night_l7d,
    count_event_id_is_others_is_late_night_l14d,
    count_event_id_is_others_is_late_night_l30d,
    count_event_id_is_others_is_late_night_all_time,
    count_event_id_is_others_is_early_morning_l7d,
    count_event_id_is_others_is_early_morning_l14d,
    count_event_id_is_others_is_early_morning_l30d,
    count_event_id_is_others_is_early_morning_all_time,
    count_event_id_is_others_is_office_hours_l7d,
    count_event_id_is_others_is_office_hours_l14d,
    count_event_id_is_others_is_office_hours_l30d,
    count_event_id_is_others_is_office_hours_all_time,
    count_event_id_is_others_is_evening_leisure_l7d,
    count_event_id_is_others_is_evening_leisure_l14d,
    count_event_id_is_others_is_evening_leisure_l30d,
    count_event_id_is_others_is_evening_leisure_all_time,
    count_event_id_is_login_success_l7d,
    count_event_id_is_login_success_l14d,
    count_event_id_is_login_success_l30d,
    count_event_id_is_login_success_all_time,
    count_event_id_is_login_success_is_late_night_l7d,
    count_event_id_is_login_success_is_late_night_l14d,
    count_event_id_is_login_success_is_late_night_l30d,
    count_event_id_is_login_success_is_late_night_all_time,
    count_event_id_is_login_success_is_early_morning_l7d,
    count_event_id_is_login_success_is_early_morning_l14d,
    count_event_id_is_login_success_is_early_morning_l30d,
    count_event_id_is_login_success_is_early_morning_all_time,
    count_event_id_is_login_success_is_office_hours_l7d,
    count_event_id_is_login_success_is_office_hours_l14d,
    count_event_id_is_login_success_is_office_hours_l30d,
    count_event_id_is_login_success_is_office_hours_all_time,
    count_event_id_is_login_success_is_evening_leisure_l7d,
    count_event_id_is_login_success_is_evening_leisure_l14d,
    count_event_id_is_login_success_is_evening_leisure_l30d,
    count_event_id_is_login_success_is_evening_leisure_all_time,
    count_event_id_is_login_success_is_ios_l7d,
    count_event_id_is_login_success_is_ios_l14d,
    count_event_id_is_login_success_is_ios_l30d,
    count_event_id_is_login_success_is_ios_all_time,
    count_event_id_is_login_success_is_ios_is_late_night_l7d,
    count_event_id_is_login_success_is_ios_is_late_night_l14d,
    count_event_id_is_login_success_is_ios_is_late_night_l30d,
    count_event_id_is_login_success_is_ios_is_late_night_all_time,
    count_event_id_is_login_success_is_ios_is_early_morning_l7d,
    count_event_id_is_login_success_is_ios_is_early_morning_l14d,
    count_event_id_is_login_success_is_ios_is_early_morning_l30d,
    count_event_id_is_login_success_is_ios_is_early_morning_all_time,
    count_event_id_is_login_success_is_ios_is_office_hours_l7d,
    count_event_id_is_login_success_is_ios_is_office_hours_l14d,
    count_event_id_is_login_success_is_ios_is_office_hours_l30d,
    count_event_id_is_login_success_is_ios_is_office_hours_all_time,
    count_event_id_is_login_success_is_ios_is_evening_leisure_l7d,
    count_event_id_is_login_success_is_ios_is_evening_leisure_l14d,
    count_event_id_is_login_success_is_ios_is_evening_leisure_l30d,
    count_event_id_is_login_success_is_ios_is_evening_leisure_all_time,
    count_event_id_is_login_success_is_android_l7d,
    count_event_id_is_login_success_is_android_l14d,
    count_event_id_is_login_success_is_android_l30d,
    count_event_id_is_login_success_is_android_all_time,
    count_event_id_is_login_success_is_android_is_late_night_l7d,
    count_event_id_is_login_success_is_android_is_late_night_l14d,
    count_event_id_is_login_success_is_android_is_late_night_l30d,
    count_event_id_is_login_success_is_android_is_late_night_all_time,
    count_event_id_is_login_success_is_android_is_early_morning_l7d,
    count_event_id_is_login_success_is_android_is_early_morning_l14d,
    count_event_id_is_login_success_is_android_is_early_morning_l30d,
    count_event_id_is_login_success_is_android_is_early_morning_all_time,
    count_event_id_is_login_success_is_android_is_office_hours_l7d,
    count_event_id_is_login_success_is_android_is_office_hours_l14d,
    count_event_id_is_login_success_is_android_is_office_hours_l30d,
    count_event_id_is_login_success_is_android_is_office_hours_all_time,
    count_event_id_is_login_success_is_android_is_evening_leisure_l7d,
    count_event_id_is_login_success_is_android_is_evening_leisure_l14d,
    count_event_id_is_login_success_is_android_is_evening_leisure_l30d,
    count_event_id_is_login_success_is_android_is_evening_leisure_all_time,
    count_event_id_is_login_success_is_others_l7d,
    count_event_id_is_login_success_is_others_l14d,
    count_event_id_is_login_success_is_others_l30d,
    count_event_id_is_login_success_is_others_all_time,
    count_event_id_is_login_success_is_others_is_late_night_l7d,
    count_event_id_is_login_success_is_others_is_late_night_l14d,
    count_event_id_is_login_success_is_others_is_late_night_l30d,
    count_event_id_is_login_success_is_others_is_late_night_all_time,
    count_event_id_is_login_success_is_others_is_early_morning_l7d,
    count_event_id_is_login_success_is_others_is_early_morning_l14d,
    count_event_id_is_login_success_is_others_is_early_morning_l30d,
    count_event_id_is_login_success_is_others_is_early_morning_all_time,
    count_event_id_is_login_success_is_others_is_office_hours_l7d,
    count_event_id_is_login_success_is_others_is_office_hours_l14d,
    count_event_id_is_login_success_is_others_is_office_hours_l30d,
    count_event_id_is_login_success_is_others_is_office_hours_all_time,
    count_event_id_is_login_success_is_others_is_evening_leisure_l7d,
    count_event_id_is_login_success_is_others_is_evening_leisure_l14d,
    count_event_id_is_login_success_is_others_is_evening_leisure_l30d,
    count_event_id_is_login_success_is_others_is_evening_leisure_all_time,
    count_event_id_is_login_failed_l7d,
    count_event_id_is_login_failed_l14d,
    count_event_id_is_login_failed_l30d,
    count_event_id_is_login_failed_all_time,
    count_event_id_is_login_failed_is_late_night_l7d,
    count_event_id_is_login_failed_is_late_night_l14d,
    count_event_id_is_login_failed_is_late_night_l30d,
    count_event_id_is_login_failed_is_late_night_all_time,
    count_event_id_is_login_failed_is_early_morning_l7d,
    count_event_id_is_login_failed_is_early_morning_l14d,
    count_event_id_is_login_failed_is_early_morning_l30d,
    count_event_id_is_login_failed_is_early_morning_all_time,
    count_event_id_is_login_failed_is_office_hours_l7d,
    count_event_id_is_login_failed_is_office_hours_l14d,
    count_event_id_is_login_failed_is_office_hours_l30d,
    count_event_id_is_login_failed_is_office_hours_all_time,
    count_event_id_is_login_failed_is_evening_leisure_l7d,
    count_event_id_is_login_failed_is_evening_leisure_l14d,
    count_event_id_is_login_failed_is_evening_leisure_l30d,
    count_event_id_is_login_failed_is_evening_leisure_all_time,
    count_event_id_is_login_failed_is_ios_l7d,
    count_event_id_is_login_failed_is_ios_l14d,
    count_event_id_is_login_failed_is_ios_l30d,
    count_event_id_is_login_failed_is_ios_all_time,
    count_event_id_is_login_failed_is_ios_is_late_night_l7d,
    count_event_id_is_login_failed_is_ios_is_late_night_l14d,
    count_event_id_is_login_failed_is_ios_is_late_night_l30d,
    count_event_id_is_login_failed_is_ios_is_late_night_all_time,
    count_event_id_is_login_failed_is_ios_is_early_morning_l7d,
    count_event_id_is_login_failed_is_ios_is_early_morning_l14d,
    count_event_id_is_login_failed_is_ios_is_early_morning_l30d,
    count_event_id_is_login_failed_is_ios_is_early_morning_all_time,
    count_event_id_is_login_failed_is_ios_is_office_hours_l7d,
    count_event_id_is_login_failed_is_ios_is_office_hours_l14d,
    count_event_id_is_login_failed_is_ios_is_office_hours_l30d,
    count_event_id_is_login_failed_is_ios_is_office_hours_all_time,
    count_event_id_is_login_failed_is_ios_is_evening_leisure_l7d,
    count_event_id_is_login_failed_is_ios_is_evening_leisure_l14d,
    count_event_id_is_login_failed_is_ios_is_evening_leisure_l30d,
    count_event_id_is_login_failed_is_ios_is_evening_leisure_all_time,
    count_event_id_is_login_failed_is_android_l7d,
    count_event_id_is_login_failed_is_android_l14d,
    count_event_id_is_login_failed_is_android_l30d,
    count_event_id_is_login_failed_is_android_all_time,
    count_event_id_is_login_failed_is_android_is_late_night_l7d,
    count_event_id_is_login_failed_is_android_is_late_night_l14d,
    count_event_id_is_login_failed_is_android_is_late_night_l30d,
    count_event_id_is_login_failed_is_android_is_late_night_all_time,
    count_event_id_is_login_failed_is_android_is_early_morning_l7d,
    count_event_id_is_login_failed_is_android_is_early_morning_l14d,
    count_event_id_is_login_failed_is_android_is_early_morning_l30d,
    count_event_id_is_login_failed_is_android_is_early_morning_all_time,
    count_event_id_is_login_failed_is_android_is_office_hours_l7d,
    count_event_id_is_login_failed_is_android_is_office_hours_l14d,
    count_event_id_is_login_failed_is_android_is_office_hours_l30d,
    count_event_id_is_login_failed_is_android_is_office_hours_all_time,
    count_event_id_is_login_failed_is_android_is_evening_leisure_l7d,
    count_event_id_is_login_failed_is_android_is_evening_leisure_l14d,
    count_event_id_is_login_failed_is_android_is_evening_leisure_l30d,
    count_event_id_is_login_failed_is_android_is_evening_leisure_all_time,
    count_event_id_is_login_failed_is_others_l7d,
    count_event_id_is_login_failed_is_others_l14d,
    count_event_id_is_login_failed_is_others_l30d,
    count_event_id_is_login_failed_is_others_all_time,
    count_event_id_is_login_failed_is_others_is_late_night_l7d,
    count_event_id_is_login_failed_is_others_is_late_night_l14d,
    count_event_id_is_login_failed_is_others_is_late_night_l30d,
    count_event_id_is_login_failed_is_others_is_late_night_all_time,
    count_event_id_is_login_failed_is_others_is_early_morning_l7d,
    count_event_id_is_login_failed_is_others_is_early_morning_l14d,
    count_event_id_is_login_failed_is_others_is_early_morning_l30d,
    count_event_id_is_login_failed_is_others_is_early_morning_all_time,
    count_event_id_is_login_failed_is_others_is_office_hours_l7d,
    count_event_id_is_login_failed_is_others_is_office_hours_l14d,
    count_event_id_is_login_failed_is_others_is_office_hours_l30d,
    count_event_id_is_login_failed_is_others_is_office_hours_all_time,
    count_event_id_is_login_failed_is_others_is_evening_leisure_l7d,
    count_event_id_is_login_failed_is_others_is_evening_leisure_l14d,
    count_event_id_is_login_failed_is_others_is_evening_leisure_l30d,
    count_event_id_is_login_failed_is_others_is_evening_leisure_all_time,

    -- device_id / count_distinct ------------------------------------------
    count_distinct_device_id_l7d,
    count_distinct_device_id_l14d,
    count_distinct_device_id_l30d,
    count_distinct_device_id_all_time,
    count_distinct_device_id_is_ios_l7d,
    count_distinct_device_id_is_ios_l14d,
    count_distinct_device_id_is_ios_l30d,
    count_distinct_device_id_is_ios_all_time,
    count_distinct_device_id_is_android_l7d,
    count_distinct_device_id_is_android_l14d,
    count_distinct_device_id_is_android_l30d,
    count_distinct_device_id_is_android_all_time,
    count_distinct_device_id_is_others_l7d,
    count_distinct_device_id_is_others_l14d,
    count_distinct_device_id_is_others_l30d,
    count_distinct_device_id_is_others_all_time,
    count_distinct_device_id_is_login_success_l7d,
    count_distinct_device_id_is_login_success_l14d,
    count_distinct_device_id_is_login_success_l30d,
    count_distinct_device_id_is_login_success_all_time,
    count_distinct_device_id_is_login_success_is_ios_l7d,
    count_distinct_device_id_is_login_success_is_ios_l14d,
    count_distinct_device_id_is_login_success_is_ios_l30d,
    count_distinct_device_id_is_login_success_is_ios_all_time,
    count_distinct_device_id_is_login_success_is_android_l7d,
    count_distinct_device_id_is_login_success_is_android_l14d,
    count_distinct_device_id_is_login_success_is_android_l30d,
    count_distinct_device_id_is_login_success_is_android_all_time,
    count_distinct_device_id_is_login_success_is_others_l7d,
    count_distinct_device_id_is_login_success_is_others_l14d,
    count_distinct_device_id_is_login_success_is_others_l30d,
    count_distinct_device_id_is_login_success_is_others_all_time,
    count_distinct_device_id_is_login_failed_l7d,
    count_distinct_device_id_is_login_failed_l14d,
    count_distinct_device_id_is_login_failed_l30d,
    count_distinct_device_id_is_login_failed_all_time,
    count_distinct_device_id_is_login_failed_is_ios_l7d,
    count_distinct_device_id_is_login_failed_is_ios_l14d,
    count_distinct_device_id_is_login_failed_is_ios_l30d,
    count_distinct_device_id_is_login_failed_is_ios_all_time,
    count_distinct_device_id_is_login_failed_is_android_l7d,
    count_distinct_device_id_is_login_failed_is_android_l14d,
    count_distinct_device_id_is_login_failed_is_android_l30d,
    count_distinct_device_id_is_login_failed_is_android_all_time,
    count_distinct_device_id_is_login_failed_is_others_l7d,
    count_distinct_device_id_is_login_failed_is_others_l14d,
    count_distinct_device_id_is_login_failed_is_others_l30d,
    count_distinct_device_id_is_login_failed_is_others_all_time,

    -- event_timestamp / min -----------------------------------------------
    min_event_timestamp_l7d,
    min_event_timestamp_l14d,
    min_event_timestamp_l30d,
    min_event_timestamp_all_time,
    min_event_timestamp_is_ios_l7d,
    min_event_timestamp_is_ios_l14d,
    min_event_timestamp_is_ios_l30d,
    min_event_timestamp_is_ios_all_time,
    min_event_timestamp_is_android_l7d,
    min_event_timestamp_is_android_l14d,
    min_event_timestamp_is_android_l30d,
    min_event_timestamp_is_android_all_time,
    min_event_timestamp_is_others_l7d,
    min_event_timestamp_is_others_l14d,
    min_event_timestamp_is_others_l30d,
    min_event_timestamp_is_others_all_time,
    min_event_timestamp_is_login_success_l7d,
    min_event_timestamp_is_login_success_l14d,
    min_event_timestamp_is_login_success_l30d,
    min_event_timestamp_is_login_success_all_time,
    min_event_timestamp_is_login_success_is_ios_l7d,
    min_event_timestamp_is_login_success_is_ios_l14d,
    min_event_timestamp_is_login_success_is_ios_l30d,
    min_event_timestamp_is_login_success_is_ios_all_time,
    min_event_timestamp_is_login_success_is_android_l7d,
    min_event_timestamp_is_login_success_is_android_l14d,
    min_event_timestamp_is_login_success_is_android_l30d,
    min_event_timestamp_is_login_success_is_android_all_time,
    min_event_timestamp_is_login_success_is_others_l7d,
    min_event_timestamp_is_login_success_is_others_l14d,
    min_event_timestamp_is_login_success_is_others_l30d,
    min_event_timestamp_is_login_success_is_others_all_time,
    min_event_timestamp_is_login_failed_l7d,
    min_event_timestamp_is_login_failed_l14d,
    min_event_timestamp_is_login_failed_l30d,
    min_event_timestamp_is_login_failed_all_time,
    min_event_timestamp_is_login_failed_is_ios_l7d,
    min_event_timestamp_is_login_failed_is_ios_l14d,
    min_event_timestamp_is_login_failed_is_ios_l30d,
    min_event_timestamp_is_login_failed_is_ios_all_time,
    min_event_timestamp_is_login_failed_is_android_l7d,
    min_event_timestamp_is_login_failed_is_android_l14d,
    min_event_timestamp_is_login_failed_is_android_l30d,
    min_event_timestamp_is_login_failed_is_android_all_time,
    min_event_timestamp_is_login_failed_is_others_l7d,
    min_event_timestamp_is_login_failed_is_others_l14d,
    min_event_timestamp_is_login_failed_is_others_l30d,
    min_event_timestamp_is_login_failed_is_others_all_time,

    -- event_timestamp / max -----------------------------------------------
    max_event_timestamp_l7d,
    max_event_timestamp_l14d,
    max_event_timestamp_l30d,
    max_event_timestamp_all_time,
    max_event_timestamp_is_ios_l7d,
    max_event_timestamp_is_ios_l14d,
    max_event_timestamp_is_ios_l30d,
    max_event_timestamp_is_ios_all_time,
    max_event_timestamp_is_android_l7d,
    max_event_timestamp_is_android_l14d,
    max_event_timestamp_is_android_l30d,
    max_event_timestamp_is_android_all_time,
    max_event_timestamp_is_others_l7d,
    max_event_timestamp_is_others_l14d,
    max_event_timestamp_is_others_l30d,
    max_event_timestamp_is_others_all_time,
    max_event_timestamp_is_login_success_l7d,
    max_event_timestamp_is_login_success_l14d,
    max_event_timestamp_is_login_success_l30d,
    max_event_timestamp_is_login_success_all_time,
    max_event_timestamp_is_login_success_is_ios_l7d,
    max_event_timestamp_is_login_success_is_ios_l14d,
    max_event_timestamp_is_login_success_is_ios_l30d,
    max_event_timestamp_is_login_success_is_ios_all_time,
    max_event_timestamp_is_login_success_is_android_l7d,
    max_event_timestamp_is_login_success_is_android_l14d,
    max_event_timestamp_is_login_success_is_android_l30d,
    max_event_timestamp_is_login_success_is_android_all_time,
    max_event_timestamp_is_login_success_is_others_l7d,
    max_event_timestamp_is_login_success_is_others_l14d,
    max_event_timestamp_is_login_success_is_others_l30d,
    max_event_timestamp_is_login_success_is_others_all_time,
    max_event_timestamp_is_login_failed_l7d,
    max_event_timestamp_is_login_failed_l14d,
    max_event_timestamp_is_login_failed_l30d,
    max_event_timestamp_is_login_failed_all_time,
    max_event_timestamp_is_login_failed_is_ios_l7d,
    max_event_timestamp_is_login_failed_is_ios_l14d,
    max_event_timestamp_is_login_failed_is_ios_l30d,
    max_event_timestamp_is_login_failed_is_ios_all_time,
    max_event_timestamp_is_login_failed_is_android_l7d,
    max_event_timestamp_is_login_failed_is_android_l14d,
    max_event_timestamp_is_login_failed_is_android_l30d,
    max_event_timestamp_is_login_failed_is_android_all_time,
    max_event_timestamp_is_login_failed_is_others_l7d,
    max_event_timestamp_is_login_failed_is_others_l14d,
    max_event_timestamp_is_login_failed_is_others_l30d,
    max_event_timestamp_is_login_failed_is_others_all_time,

    -- days_since_login / min ----------------------------------------------
    {{ fs_datediff_day("max_event_timestamp_l7d", fs_target_date()) }} as min_days_since_login_l7d,
    {{ fs_datediff_day("max_event_timestamp_l14d", fs_target_date()) }} as min_days_since_login_l14d,
    {{ fs_datediff_day("max_event_timestamp_l30d", fs_target_date()) }} as min_days_since_login_l30d,
    {{ fs_datediff_day("max_event_timestamp_all_time", fs_target_date()) }} as min_days_since_login_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_ios_l7d", fs_target_date()) }} as min_days_since_login_is_ios_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_ios_l14d", fs_target_date()) }} as min_days_since_login_is_ios_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_ios_l30d", fs_target_date()) }} as min_days_since_login_is_ios_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_ios_all_time", fs_target_date()) }} as min_days_since_login_is_ios_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_android_l7d", fs_target_date()) }} as min_days_since_login_is_android_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_android_l14d", fs_target_date()) }} as min_days_since_login_is_android_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_android_l30d", fs_target_date()) }} as min_days_since_login_is_android_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_android_all_time", fs_target_date()) }} as min_days_since_login_is_android_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_others_l7d", fs_target_date()) }} as min_days_since_login_is_others_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_others_l14d", fs_target_date()) }} as min_days_since_login_is_others_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_others_l30d", fs_target_date()) }} as min_days_since_login_is_others_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_others_all_time", fs_target_date()) }} as min_days_since_login_is_others_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_l7d", fs_target_date()) }} as min_days_since_login_is_login_success_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_l14d", fs_target_date()) }} as min_days_since_login_is_login_success_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_l30d", fs_target_date()) }} as min_days_since_login_is_login_success_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_all_time", fs_target_date()) }} as min_days_since_login_is_login_success_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_ios_l7d", fs_target_date()) }} as min_days_since_login_is_login_success_is_ios_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_ios_l14d", fs_target_date()) }} as min_days_since_login_is_login_success_is_ios_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_ios_l30d", fs_target_date()) }} as min_days_since_login_is_login_success_is_ios_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_ios_all_time", fs_target_date()) }} as min_days_since_login_is_login_success_is_ios_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_android_l7d", fs_target_date()) }} as min_days_since_login_is_login_success_is_android_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_android_l14d", fs_target_date()) }} as min_days_since_login_is_login_success_is_android_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_android_l30d", fs_target_date()) }} as min_days_since_login_is_login_success_is_android_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_android_all_time", fs_target_date()) }} as min_days_since_login_is_login_success_is_android_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_others_l7d", fs_target_date()) }} as min_days_since_login_is_login_success_is_others_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_others_l14d", fs_target_date()) }} as min_days_since_login_is_login_success_is_others_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_others_l30d", fs_target_date()) }} as min_days_since_login_is_login_success_is_others_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_success_is_others_all_time", fs_target_date()) }} as min_days_since_login_is_login_success_is_others_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_l7d", fs_target_date()) }} as min_days_since_login_is_login_failed_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_l14d", fs_target_date()) }} as min_days_since_login_is_login_failed_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_l30d", fs_target_date()) }} as min_days_since_login_is_login_failed_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_all_time", fs_target_date()) }} as min_days_since_login_is_login_failed_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_ios_l7d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_ios_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_ios_l14d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_ios_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_ios_l30d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_ios_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_ios_all_time", fs_target_date()) }} as min_days_since_login_is_login_failed_is_ios_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_android_l7d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_android_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_android_l14d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_android_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_android_l30d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_android_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_android_all_time", fs_target_date()) }} as min_days_since_login_is_login_failed_is_android_all_time,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_others_l7d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_others_l7d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_others_l14d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_others_l14d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_others_l30d", fs_target_date()) }} as min_days_since_login_is_login_failed_is_others_l30d,
    {{ fs_datediff_day("max_event_timestamp_is_login_failed_is_others_all_time", fs_target_date()) }} as min_days_since_login_is_login_failed_is_others_all_time,

    -- days_since_login / max ----------------------------------------------
    {{ fs_datediff_day("min_event_timestamp_l7d", fs_target_date()) }} as max_days_since_login_l7d,
    {{ fs_datediff_day("min_event_timestamp_l14d", fs_target_date()) }} as max_days_since_login_l14d,
    {{ fs_datediff_day("min_event_timestamp_l30d", fs_target_date()) }} as max_days_since_login_l30d,
    {{ fs_datediff_day("min_event_timestamp_all_time", fs_target_date()) }} as max_days_since_login_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_ios_l7d", fs_target_date()) }} as max_days_since_login_is_ios_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_ios_l14d", fs_target_date()) }} as max_days_since_login_is_ios_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_ios_l30d", fs_target_date()) }} as max_days_since_login_is_ios_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_ios_all_time", fs_target_date()) }} as max_days_since_login_is_ios_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_android_l7d", fs_target_date()) }} as max_days_since_login_is_android_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_android_l14d", fs_target_date()) }} as max_days_since_login_is_android_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_android_l30d", fs_target_date()) }} as max_days_since_login_is_android_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_android_all_time", fs_target_date()) }} as max_days_since_login_is_android_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_others_l7d", fs_target_date()) }} as max_days_since_login_is_others_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_others_l14d", fs_target_date()) }} as max_days_since_login_is_others_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_others_l30d", fs_target_date()) }} as max_days_since_login_is_others_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_others_all_time", fs_target_date()) }} as max_days_since_login_is_others_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_l7d", fs_target_date()) }} as max_days_since_login_is_login_success_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_l14d", fs_target_date()) }} as max_days_since_login_is_login_success_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_l30d", fs_target_date()) }} as max_days_since_login_is_login_success_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_all_time", fs_target_date()) }} as max_days_since_login_is_login_success_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_ios_l7d", fs_target_date()) }} as max_days_since_login_is_login_success_is_ios_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_ios_l14d", fs_target_date()) }} as max_days_since_login_is_login_success_is_ios_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_ios_l30d", fs_target_date()) }} as max_days_since_login_is_login_success_is_ios_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_ios_all_time", fs_target_date()) }} as max_days_since_login_is_login_success_is_ios_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_android_l7d", fs_target_date()) }} as max_days_since_login_is_login_success_is_android_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_android_l14d", fs_target_date()) }} as max_days_since_login_is_login_success_is_android_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_android_l30d", fs_target_date()) }} as max_days_since_login_is_login_success_is_android_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_android_all_time", fs_target_date()) }} as max_days_since_login_is_login_success_is_android_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_others_l7d", fs_target_date()) }} as max_days_since_login_is_login_success_is_others_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_others_l14d", fs_target_date()) }} as max_days_since_login_is_login_success_is_others_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_others_l30d", fs_target_date()) }} as max_days_since_login_is_login_success_is_others_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_success_is_others_all_time", fs_target_date()) }} as max_days_since_login_is_login_success_is_others_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_l7d", fs_target_date()) }} as max_days_since_login_is_login_failed_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_l14d", fs_target_date()) }} as max_days_since_login_is_login_failed_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_l30d", fs_target_date()) }} as max_days_since_login_is_login_failed_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_all_time", fs_target_date()) }} as max_days_since_login_is_login_failed_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_ios_l7d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_ios_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_ios_l14d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_ios_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_ios_l30d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_ios_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_ios_all_time", fs_target_date()) }} as max_days_since_login_is_login_failed_is_ios_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_android_l7d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_android_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_android_l14d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_android_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_android_l30d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_android_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_android_all_time", fs_target_date()) }} as max_days_since_login_is_login_failed_is_android_all_time,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_others_l7d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_others_l7d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_others_l14d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_others_l14d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_others_l30d", fs_target_date()) }} as max_days_since_login_is_login_failed_is_others_l30d,
    {{ fs_datediff_day("min_event_timestamp_is_login_failed_is_others_all_time", fs_target_date()) }} as max_days_since_login_is_login_failed_is_others_all_time,

    _first_event_date,
    _last_event_date,
    {{ dbt.current_timestamp() }} as _generated_at,
    '35c25bc02ee1' as _spec_version
from joined
